### ISSUE TITLE
change of directory for plotting 

### ISSUE THREAD

**Issue by rohitereddy** [ohager/burst-autoplotter#33]
great tool, was recommended by a lot of people. 

it would be nice to be able to specify a directory of a disk for plotting 
Ex : Z:\My Drive\BURST.

**Comment by ohager** [comment]
I'll consider it in the next upcoming version. (Maybe this weekend already)

**Comment by ohager** [comment]
available in version 0.5

**Comment by rohitereddy** [comment]
that's wonderful, will look into it. 

thank you.
