### ISSUE TITLE
simple frontend

### ISSUE THREAD

**Issue by dynamitemedia** [ohager/burst-autoplotter#8]
i have used autoit for several projects and this  could give a very easy and good looking GUI

**Comment by ohager** [comment]
Actually, I think of an entire rewrite in C# or C++ (the latter is not my primary language anymore). NodeJS is nice, but I think it's simply too much overhead installing NodeJS for normal users. I already tried to create a standalone executable using pkg and nexe (#5), but the resulting binary is insanely large (approx. 20 MiB, 13 MiB respectively compressed with upx). When I find the time to write a Cxxx version I'll consider a neat GUI. 

Thanks for feedback....I pretty much appreciate it.

btw: I had a look at autoit - not convincing me :P
